## Function 127
## Added in 3.0
validateInputDataSexDiff <- function(Mfile, Ffile) {
    requiredColumnsMfile <- c("SNP", "CHR", "BP", "A1", "BETA_M", "SE_M")
    requiredColumnsFfile <- c("SNP", "CHR", "BP", "A1", "BETA_F", "SE_F")

    # Check if Mfile and Ffile are dataframes
    if (!is.data.frame(Mfile)) {
        stop("Error: Mfile must be a dataframe.")
    }
    if (!is.data.frame(Ffile)) {
        stop("Error: Ffile must be a dataframe.")
    }

    # Check for existence of required columns in Mfile
    missingColsMfile <- setdiff(requiredColumnsMfile, names(Mfile))
    if (length(missingColsMfile) > 0) {
        stop("Error: Mfile is missing these columns:", paste(missingColsMfile, collapse = ", "))
    }

    # Check for existence of required columns in Ffile
    missingColsFfile <- setdiff(requiredColumnsFfile, names(Ffile))
    if (length(missingColsFfile) > 0) {
        stop("Error: Ffile is missing these columns:", paste(missingColsFfile, collapse = ", "))
    }

    return(TRUE)
}

#' SexDiff: Sex difference in effect size for each SNP using t-test.
#'
#' @author Banabithi Bose
#'
#' @description
#' This function uses the GWAS summary statistics from sex-stratified tests like "FMstratified", to evaluate
#' the difference in effect size between males and females at each SNP using a t-test.
#'
#' The input dataframes should only include X-chromosome in order to obtain results for sex differences based solely
#' on X-linked loci.
#'
#' @param Mfile
#' R dataframe of summary statistics of GWAS or XWAS of male samples with six mandatory columns, SNP(Variant),CHR(Chromosome number),
#' BP(Base pair position),A1(Minor allele),BETA_M(Effect size) and SE_M(Standard error). This can be generated by running FM01comb or
#' "FMstratified" model with GXWAS function.
#'
#' @param Ffile
#' R dataframe of summary statistics of GWAS or XWAS of male samples with six mandatory columns, SNP(Variant),CHR(Chromosome number),
#' BP(Base pair position),A1(Minor allele),BETA_F(Effect size) and SE_F(Standard error). This can be generated by running FM01comb or
#' "FMstratified" model with GXWAS function.
#'
#' @return
#' R dataframe with seven columns:
#'
#' * `SNP` (Variant)
#' * `CHR` (Chromosome number)
#' * `BP` (Base pair position)
#' * `A1` (Minor allele)
#' * `tstat` (t-statistics for effect-size test)
#' * `P` (p-value) and
#' * `adjP` (Bonferroni corrected p-value)
#'
#' @importFrom stats cor pt
#'
#' @export
#'
#' @examples
#' data("Mfile", package = "GXwasR")
#' data("Ffile", package = "GXwasR")
#' Difftest <- SexDiff(Mfile, Ffile)
#' significant_snps <- Difftest[Difftest$adjP < 0.05, ]
SexDiff <- function(Mfile, Ffile) {
    # Validate input data
    if (!validateInputDataSexDiff(Mfile, Ffile)) {
        return(NULL)
    }

    tryCatch(
        {
            MFWAS <- merge(na.omit(Mfile), na.omit(Ffile), by = c("SNP", "CHR", "BP", "A1"))
            gc(reset = TRUE)

            r <-
                stats::cor(MFWAS$BETA_M, MFWAS$BETA_F, method = "spearman", use = "pairwise.complete.obs")

            MFWAS$tstat <-
                (MFWAS$BETA_M - MFWAS$BETA_F) / sqrt(((MFWAS$SE_M)^2) + (MFWAS$SE_F^2) - 2 * r * (MFWAS$SE_M) * MFWAS$SE_F)

            gc(reset = TRUE)
            MFWAS$P <- stats::pt(q = abs(MFWAS$tstat), df = 2 * nrow(MFWAS) - 2, lower.tail = FALSE)
            MFWAS <- data.table::as.data.table(MFWAS)
            MFWAS$adjP <- p.adjust(MFWAS$P, method = "bonferroni", n = nrow(MFWAS))
            gc(reset = TRUE)
            x <- MFWAS[, c("SNP", "CHR", "BP", "A1", "tstat", "P", "adjP")]
            y <- x[order(x$adjP), ]
            # qq plot
            chisq <- qchisq(1 - y$P, 1)
            lamdaGC <- median(chisq) / qchisq(0.5, 1)
            gc(reset = TRUE)
            par(mar = c(1, 1, 1, 1))
            qqman::qq(y$P, main = paste0(("QQ-plots for test of sex-differentiated\n effect size with GIF = "), round(lamdaGC, 3)))
            gc(reset = TRUE)
            return(y)
        },
        error = function(e) {
            rlang::abort(
                message = e$message, 
                class = "SexDiff_error"
            )
        },
        warning = function(w) {
            rlang::warn(
                message = w$message, 
                class = "SexDiff_warning", 
                .frequency = "regularly", 
                .frequency_id = "SexDiff_warning"
            )
        }
    )
}

## Function 143
## Added in 3.0
validateInputForSexDiffZscore <- function(inputdata) {
    # Validate inputdata - must be a dataframe
    if (!is.data.frame(inputdata)) {
        stop("Error in inputdata: Must be a dataframe.")
    }

    # Validate required columns in inputdata
    required_cols <- c("Fstat", "Fse", "Mstat", "Mse")
    if (!all(required_cols %in% names(inputdata))) {
        stop("Error in inputdata: Dataframe must contain columns 'Fstat', 'Fse', 'Mstat', 'Mse'.")
    }

    return(TRUE)
}

#' SexDiffZscore: Z-score-based sex difference test.
#'
#' @description
#' This function calculates the difference in any kind of measured entities,(example: including SNP heritability estimate,
#' genetic correlation, and GWAS \eqn{\beta} values) between sexes using a Z-score and its associated p-value statistic.
#' When STAT/SE is normally distributed and the test statistics are independent in sex, the test is well calibrated. If
#' the statistics are positively correlated, this test is conservative (1).
#'
#' We could define SNPs with SDEs as those variants at the extreme ends of the distribution with an absolute value of the
#' Z-score greater than 3(|Z-score| > 3), which is roughly equivalent to p <10-3, and represents 0.3% of all tested SNPs.
#' The input dataframes should only include X-chromosome in order to obtain results for sex differences based solely on
#' X-linked loci.
#'
#' @param inputdata
#' A dataframe with five columns:
#' * `ID` (i.e., SNP ID or the phenotype of interest, etc.)
#' * `Fstat` (i.e., the measured statistics in females)
#' * `Fse` (i.e., the standard error of the measured statistics in females)
#' * `Mstat` (i.e., the measured statistics in males)
#' * `Mse` (i.e., the standard error of the measured statistics in males)
#'
#'
#' @return
#' Original input dataframe with:
#' * `Zscore` (i.e., Z-score),
#' * `p` (i.e., p-value) and
#' * `adjP` (i.e., Bonferroni corrected p-value)
#' columns added.
#'
#' @export
#'
#' @examples
#' data("Example_h2data", package = "GXwasR")
#' inputdata <- Example_h2data
#' x <- SexDiffZscore(inputdata)
#'
SexDiffZscore <- function(inputdata) {
    # Validate input parameters
    validateInputForSexDiffZscore(inputdata)

    tryCatch(
        {
            inputdata$x <- as.numeric(inputdata$Mstat) - as.numeric(inputdata$Fstat)
            inputdata$y <- sqrt((as.numeric(inputdata$Mse))^2 + (as.numeric(inputdata$Fse))^2)
            inputdata$Zscore <- inputdata$x / inputdata$y

            # Calculate p-values
            inputdata$p <- 2 * pnorm(-abs(inputdata$Zscore))
            inputdata$adjP <- p.adjust(inputdata$p, method = "bonferroni")

            inputdata <- inputdata[, c("ID", "Mstat", "Mse", "Fstat", "Fse", "Zscore", "p", "adjP")]
            return(inputdata)
        },
        error = function(e) {
            rlang::abort(
                message = e$message,
                class = "SexDiffZscore_error"
            )
        },
        warning = function(w) {
            rlang::warn(
                message = w$message,
                class = "SexDiffZscore_warning",
                .frequency = "regularly",
                .frequency_id = "SexDiffZscore_warning"
            )
        }
    )
}

## Function 142
## Added in 3.0
validateInputForDiffZeroOne <- function(inputdata, diffzero, diffone) {
    # Validate inputdata - must be a dataframe
    if (!is.data.frame(inputdata)) {
        stop("Error in inputdata: Must be a dataframe.")
    }

    # Validate required columns in inputdata
    required_cols <- c("Stat", "SE")
    if (!all(required_cols %in% names(inputdata))) {
        stop("Error in inputdata: Dataframe must contain columns 'Stat' and 'SE'.")
    }

    # Validate diffzero - must be a single boolean value
    if (!is.logical(diffzero) || length(diffzero) != 1) {
        stop("Error in diffzero: Must be a single boolean value.")
    }

    # Validate diffone - must be a single boolean value
    if (!is.logical(diffone) || length(diffone) != 1) {
        stop("Error in diffone: Must be a single boolean value.")
    }

    return(TRUE)
}


#' DiffZeroOne: Assessing the Z-score for deviation from one and zero.
#'
#' @description
#' This function tests the null hypothesis that a measured statistics (example: genetic correlation,
#' rg for a trait) < 1 using a 1-tailed test compared with a normal distribution (z = (1 - measure statistics)/Standard error).
#' For multiple tests, users are encouraged to apply a Bonferroni multiple-testing correction.
#'
#' @param inputdata
#' A dataframe object, containing three columns:
#' * `Trait` (i.e., the phenotype of interest)
#' * `Stat` (i.e., the measured statistics)
#' * `SE` (i.e., the standard error of the measured statistics)
#'
#' @param diffzero
#' Boolean value, `TRUE` or `FALSE`, specifying to perform deviation from 0 test.
#'
#' @param diffone
#' Boolean value, `TRUE` or `FALSE`, specifying to perform deviation from 1 test.
#'
#' @return
#' A dataframe with columns:
#' * `Trait`
#' * `Stat`
#' * `SE`
#' * `P0` (i.e, p-value for deviation from zero test)
#' * `P1` (i.e., p-value for deviation from 1 test)
#'
#' @export
#'
#' @examples
#' data("Example_rgdata", package = "GXwasR")
#' inputdata <- Example_rgdata
#' colnames(inputdata) <- c("Trait", "Stat", "SE")
#' x <- DiffZeroOne(inputdata, FALSE, TRUE)
DiffZeroOne <- function(inputdata, diffzero = TRUE, diffone = TRUE) {
    validateInputForDiffZeroOne(inputdata, diffzero, diffone)

    tryCatch(
        {
            if (diffzero == FALSE & diffone == FALSE) {
                rlang::inform(rlang::format_error_bullets(c("x" = "Both diffzero and diffone cannot set to be FALSE.")))
                return()
            } else if (diffzero == TRUE && diffone == TRUE) {
                inputdata1 <- inputdata
                inputdata$x <- as.numeric(inputdata$Stat)
                inputdata$y <- as.numeric(inputdata$SE)
                inputdata$Zscore <- inputdata$x / inputdata$y
                inputdata1$p0 <- pnorm(inputdata$Zscore, mean = 0, sd = 1, lower.tail = FALSE) # one-tailed p-value

                inputdata$x <- 1 - as.numeric(inputdata$Stat)
                inputdata$y <- as.numeric(inputdata$SE)
                inputdata$Zscore <- inputdata$x / inputdata$y
                inputdata1$p1 <- pnorm(inputdata$Zscore, mean = 0, sd = 1, lower.tail = FALSE) # one-tailed p-value
            } else if (diffzero == FALSE && diffone == TRUE) {
                inputdata1 <- inputdata
                inputdata$x <- 1 - as.numeric(inputdata$Stat)
                inputdata$y <- as.numeric(inputdata$SE)
                inputdata$Zscore <- inputdata$x / inputdata$y
                inputdata1$p1 <- pnorm(inputdata$Zscore, mean = 0, sd = 1, lower.tail = FALSE) # one-tailed p-value
            } else if (diffzero == TRUE && diffone == FALSE) {
                inputdata1 <- inputdata
                inputdata$x <- as.numeric(inputdata$Stat)
                inputdata$y <- as.numeric(inputdata$SE)
                inputdata$Zscore <- inputdata$x / inputdata$y
                inputdata1$p0 <- pnorm(inputdata$Zscore, mean = 0, sd = 1, lower.tail = FALSE) # one-tailed p-value
            }

            return(inputdata1)
        },
        error = function(e) {
            rlang::abort(
                message = e_message,
                class = "DiffZeroOne_error"
            )
        },
        warning = function(w) {
            rlang::warn(
                message = w_message,
                class = "DiffZeroOne_warning", 
                .frequency = "regularly", 
                .frequency_id = "DiffZeroOne_warning"
            )
        }
    )
}
